import List, { ListProps as MuiListProps } from '@material-ui/core/List';
import ListItem, { ListItemProps as MuiListItemProps } from '@material-ui/core/ListItem';
import ListItemIcon, { ListItemIconProps as MuiListItemIconProps } from '@material-ui/core/ListItemIcon';
import ListItemText, { ListItemTextProps as MuiListItemTextProps } from '@material-ui/core/ListItemText';
export declare type ListProps = MuiListProps;
export declare type ListItemProps = MuiListItemProps;
export declare type ListItemIconProps = MuiListItemIconProps;
export declare type ListItemTextProps = MuiListItemTextProps;
export { List, ListItem, ListItemIcon, ListItemText };
export default List;
