import DateFnsUtils from '@date-io/date-fns';
import { TimePickerProps as MuiTimePickerProps, KeyboardDatePickerProps as MuiKeyboardDatePickerProps, KeyboardTimePickerProps as MuiKeyboardTimePickerProps, MuiPickersUtilsProvider as PickersUtilsProvider } from '@material-ui/pickers';
import * as React from 'react';
export declare type TimePickerProps = MuiTimePickerProps;
export declare type KeyboardDatePickerProps = MuiKeyboardDatePickerProps;
export declare type KeyboardTimePickerProps = MuiKeyboardTimePickerProps;
declare const TimePicker: React.FC<TimePickerProps>;
declare const KeyboardDatePicker: React.FC<KeyboardDatePickerProps>;
declare const KeyboardTimePicker: React.FC<KeyboardTimePickerProps>;
export { TimePicker, KeyboardDatePicker, KeyboardTimePicker, PickersUtilsProvider, DateFnsUtils };
export default TimePicker;
