import { TableProps as PropsTable } from '@material-ui/core/Table';
import { TableBodyProps as PropsTableBody } from '@material-ui/core/TableBody';
import { TableCellProps as PropsTableCell } from '@material-ui/core/TableCell';
import { TableContainerProps as PropsTableContainer } from '@material-ui/core/TableContainer';
import { TableFooterProps as PropsTableFooter } from '@material-ui/core/TableFooter';
import { TableHeadProps as PropsTableHead } from '@material-ui/core/TableHead';
import { TablePaginationProps as PropsTablePagination } from '@material-ui/core/TablePagination';
import { TableRowProps as PropsTableRow } from '@material-ui/core/TableRow';
import { TableSortLabelProps as PropsTableSortLabel } from '@material-ui/core/TableSortLabel';
import * as React from 'react';
export declare type TableProps = PropsTable;
export declare type TableBodyProps = PropsTableBody;
export declare type TableCellProps = PropsTableCell;
export declare type TableContainerProps = PropsTableContainer;
export declare type TableFooterProps = PropsTableFooter;
export declare type TableHeadProps = PropsTableHead;
export declare type TablePaginationProps = PropsTablePagination;
export declare type TableRowProps = PropsTableRow;
export declare type TableSortLabelProps = PropsTableSortLabel;
export declare const Table: React.FC<TableProps>;
export declare const TableBody: React.FC<TableBodyProps>;
export declare const TableCell: React.FC<TableCellProps>;
export declare const TableContainer: React.FC<TableContainerProps>;
export declare const TableFooter: React.FC<TableFooterProps>;
export declare const TableHead: React.FC<TableHeadProps>;
export declare const TablePagination: React.FC<TablePaginationProps>;
export declare const TableRow: React.FC<TableRowProps>;
export declare const TableSortLabel: React.FC<TableSortLabelProps>;
